const KEEP_ALIVE_INTERVAL = 300000 // 5 minutes in milliseconds

const BACKOFF = 600000 // retry exponential backoff rate in milliseconds

const LOCALES_TO_JESTA_LANGUAGE_NUMBERS = {
  'en-CA': 1,
  'fr-CA': 3
}

const JESTA_TAX_DESCRIPTIONS = {
  GST: 'GST CANADA',
  PST_BC: 'PST-BC',
  PST_SK: 'PST-SK',
  PST_MB: 'PST-MB',
  HST_ON: 'HST-ON',
  QST_QC: 'QST-QC',
  HST_NB: 'HST-NB',
  HST_NL: 'HST-NFL',
  HST_NS: 'HST-NS',
  HST_PE: 'HST-PEI'
}

const CARD_TYPES_TO_JESTA_CODES = {
  visa: '05',
  mastercard: '06',
  'american-express': '07',
  'diners-club': '09',
  discover: '08',
  jcb: '10'
}

const PAYMENT_METHODS_TO_JESTA_CODES = {
  // TODO: complete after given info from Bold
}

const ONLINE_SITE_ID = '990'

const HEADER_ROWS_ENUM = {
  RECORD_TYPE: 'RecordType H',
  SITE_ID: 'SITE_ID',
  WFE_TRANS_ID: 'WFE_TRANS_ID',
  SHIP_TO_FIRST_NAME: 'SHIP_TO_FIRST_NAME',
  SHIP_TO_LAST_NAME: 'SHIP_TO_LAST_NAME',
  SHIP_TO_ADDRESS_1: 'SHIP_TO_ADDRESS_1',
  SHIP_TO_ADDRESS_2: 'SHIP_TO_ADDRESS_2',
  SHIP_TO_ADDRESS_3: 'SHIP_TO_ADDRESS_3',
  SHIP_TO_CITY: 'SHIP_TO_CITY',
  SHIP_TO_STATE_ID: 'SHIP_TO_STATE_ID',
  SHIP_TO_ZIP_CODE: 'SHIP_TO_ZIP_CODE',
  SHIP_TO_COUNTRY_ID: 'SHIP_TO_COUNTRY_ID',
  WFE_CUSTOMER_ID: 'WFE_CUSTOMER_ID',
  BILL_TO_FIRST_NAME: 'BILL_TO_FIRST_NAME',
  BILL_TO_LAST_NAME: 'BILL_TO_LAST_NAME',
  BILL_TO_ADDRESS_1: 'BILL_TO_ADDRESS_1',
  BILL_TO_ADDRESS_2: 'BILL_TO_ADDRESS_2',
  BILL_TO_ADDRESS_3: 'BILL_TO_ADDRESS_3',
  BILL_TO_CITY: 'BILL_TO_CITY',
  BILL_TO_STATE_ID: 'BILL_TO_STATE_ID',
  BILL_TO_ZIP_CODE: 'BILL_TO_ZIP_CODE',
  BILL_TO_COUNTRY_ID: 'BILL_TO_COUNTRY_ID',
  BILL_TO_HOME_PHONE: 'BILL_TO_HOME_PHONE',
  EMAIL_ADDRESS: 'EMAIL_ADDRESS',
  CARRIER_ID: 'CARRIER_ID',
  RUSH_SHIPPING_IND: 'RUSH_SHIPPING_IND',
  SHIP_COMPLETE_IND: 'SHIP_COMPLETE_IND',
  SHIPPING_CHARGES_TOTAL: 'SHIPPING_CHARGES_TOTAL',
  TAX_TOTAL: 'TAX_TOTAL',
  TRANSACTION_TOTAL: 'TRANSACTION_TOTAL',
  POS_EQUIVALENCE: 'POS_EQUIVALENCE',
  ORDER_DATE: 'ORDER_DATE',
  ADDITIONAL_METADATA: 'ADDITIONAL_METADATA',
  SHIPPING_TAX1: 'SHIPPING_TAX1',
  SHIPPING_TAX1_DESCRIPTION: 'SHIPPING_TAX1_DESCRIPTION',
  SHIPPING_TAX2: 'SHIPPING_TAX2',
  SHIPPING_TAX2_DESCRIPTION: 'SHIPPING_TAX2_DESCRIPTION',
  SHIPPING_TAX3: 'SHIPPING_TAX3',
  SHIPPING_TAX3_DESCRIPTION: 'SHIPPING_TAX3_DESCRIPTION',
  DESTINATION_SITE_ID: 'DESTINATION_SITE_ID',
  REQUESTER_SITE_ID: 'REQUESTER_SITE_ID',
  SERVICE_TYPE: 'SERVICE_TYPE',
  LANGUAGE_NO: 'LANGUAGE_NO',
  FREE_RETURN_IND: 'FREE_RETURN_IND',
  SIGNATURE_REQUIRED_IND: 'SIGNATURE_REQUIRED_IND',
  RELEASED: 'RELEASED'
}

// We don't generate this array from the above enum because the order
// matters, and the order of the properties on JS objects isn't guaranteed.
// And we don't generate the enum from this array because my editor isn't smart
// enough to figure out how to do autocomplete unless you explicitly define the
// values of an object.
//
// Empty strings represent blank headers.
//
const HEADER_ROWS = [
  'RecordType H',
  'SITE_ID',
  'WFE_TRANS_ID',
  'SHIP_TO_FIRST_NAME',
  'SHIP_TO_LAST_NAME',
  '',
  'SHIP_TO_ADDRESS_1',
  'SHIP_TO_ADDRESS_2',
  'SHIP_TO_ADDRESS_3',
  'SHIP_TO_CITY',
  'SHIP_TO_STATE_ID',
  'SHIP_TO_ZIP_CODE',
  'SHIP_TO_COUNTRY_ID',
  'WFE_CUSTOMER_ID',
  'BILL_TO_FIRST_NAME',
  'BILL_TO_LAST_NAME',
  'BILL_TO_ADDRESS_1',
  'BILL_TO_ADDRESS_2',
  'BILL_TO_ADDRESS_3',
  'BILL_TO_CITY',
  'BILL_TO_STATE_ID',
  'BILL_TO_ZIP_CODE',
  'BILL_TO_COUNTRY_ID',
  'BILL_TO_HOME_PHONE',
  'EMAIL_ADDRESS',
  'CARRIER_ID',
  'RUSH_SHIPPING_IND',
  'SHIP_COMPLETE_IND',
  '',
  'SHIPPING_CHARGES_TOTAL',
  'TAX_TOTAL',
  '',
  'TRANSACTION_TOTAL',
  '',
  'POS_EQUIVALENCE',
  '',
  '',
  '',
  '',
  'ORDER_DATE',
  'ADDITIONAL_METADATA',
  'SHIPPING_TAX1',
  'SHIPPING_TAX1_DESCRIPTION',
  'SHIPPING_TAX2',
  'SHIPPING_TAX2_DESCRIPTION',
  'SHIPPING_TAX3',
  'SHIPPING_TAX3_DESCRIPTION',
  'DESTINATION_SITE_ID',
  'REQUESTER_SITE_ID',
  '',
  '',
  'SERVICE_TYPE',
  'LANGUAGE_NO',
  'FREE_RETURN_IND',
  'SIGNATURE_REQUIRED_IND',
  'RELEASED'
]

const DETAILS_ROWS_ENUM = {
  RECORD_TYPE: 'RecordType D',
  SITE_ID: 'SITE_ID',
  LINE: 'LINE',
  WFE_TRANS_ID: 'WFE_TRANS_ID',
  QTY_ORDERED: 'QTY_ORDERED',
  UNIT_PRICE: 'UNIT_PRICE',
  EXTENSION_AMOUNT: 'EXTENSION_AMOUNT',
  LINE_SHIPPING_CHARGES: 'LINE_SHIPPING_CHARGES',
  LINE_TOTAL_TAX: 'LINE_TOTAL_TAX',
  LINE_TOTAL_AMOUNT: 'LINE_TOTAL_AMOUNT',
  BAR_CODE_ID: 'BAR_CODE_ID',
  ENDLESS_AISLE_IND: 'ENDLESS_AISLE_IND',
  EXT_REF_ID: 'EXT_REF_ID',
  GIFT_WRAP_IND: 'GIFT_WRAP_IND',
  SALESPERSON_ID: 'SALESPERSON_ID',
  ADDITIONAL_METADATA: 'ADDITIONAL_METADATA',
  SUB_TYPE: 'SUB_TYPE'
}

const DETAILS_ROWS = [
  'RecordType D',
  'SITE_ID',
  'LINE',
  'WFE_TRANS_ID',
  '',
  '',
  '',
  'QTY_ORDERED',
  'UNIT_PRICE',
  '',
  'EXTENSION_AMOUNT',
  'LINE_SHIPPING_CHARGES',
  'LINE_TOTAL_TAX',
  'LINE_TOTAL_AMOUNT',
  'BAR_CODE_ID',
  'ENDLESS_AISLE_IND',
  'EXT_REF_ID',
  'GIFT_WRAP_IND',
  '',
  '',
  'SALESPERSON_ID',
  'ADDITIONAL_METADATA',
  'SUB_TYPE'
]

const TAXES_ROWS_ENUM = {
  RECORD_TYPE: 'RecordType T',
  SITE_ID: 'SITE_ID',
  LINE: 'LINE',
  WFE_TRANS_ID: 'WFE_TRANS_ID',
  SEQUENCE: 'SEQUENCE',
  MERCHANDISE_TAX_AMOUNT: 'MERCHANDISE_TAX_AMOUNT',
  MERCHANDISE_TAX_DESC: 'MERCHANDISE_TAX_DESC'
}

const TAXES_ROWS = [
  'RecordType T',
  'SITE_ID',
  'LINE',
  'WFE_TRANS_ID',
  'SEQUENCE',
  'MERCHANDISE_TAX_AMOUNT',
  'MERCHANDISE_TAX_DESC'
]

const TENDER_ROWS_ENUM = {
  RECORD_TYPE: 'RecordType N',
  SITE_ID: 'SITE_ID',
  LINE: 'LINE',
  WFE_TRANS_ID: 'WFE_TRANS_ID',
  AMOUNT: 'AMOUNT',
  POS_EQUIVALENCE: 'POS_EQUIVALENCE',
  REFERENCENO: 'REFERENCENO',
  EXPDATE: 'EXPDATE',
  CARD_NO: 'CARD_NO',
  AUTHORIZATION_NO: 'AUTHORIZATION_NO'
}

const TENDER_ROWS = [
  'RecordType N',
  'SITE_ID',
  'LINE',
  'WFE_TRANS_ID',
  'AMOUNT',
  'POS_EQUIVALENCE',
  'REFERENCENO',
  'EXPDATE',
  '',
  'CARD_NO',
  'AUTHORIZATION_NO'
]

const MISC_ROWS = [
  'RecordType M',
  'SITE_ID',
  'LINE',
  'WFE_TRANS_ID',
  'SEQUENCE',
  'AMOUNT',
  'REASON_ID',
  'MISC_TAX_AMOUNT1',
  'MISC_TAX_DESC1',
  'MISC_TAX_AMOUNT2',
  'MISC_TAX_DESC2'
]

const GENERAL_CSV_OPTIONS = {
  header: false,
  quote: '',
  eol: '\r\n' // The CSVs will be processed by a Windows machine
}

const SENT_TO_OMS_STATUSES = {
  SUCCESS: 'SUCCESS',
  PENDING: 'PENDING',
  FAILURE: 'FAILURE'
}

const SEND_ORDER_RETRY_LIMIT = 5

module.exports = {
  BACKOFF,
  CARD_TYPES_TO_JESTA_CODES,
  DETAILS_ROWS,
  DETAILS_ROWS_ENUM,
  GENERAL_CSV_OPTIONS,
  JESTA_TAX_DESCRIPTIONS,
  LOCALES_TO_JESTA_LANGUAGE_NUMBERS,
  HEADER_ROWS,
  HEADER_ROWS_ENUM,
  KEEP_ALIVE_INTERVAL,
  MISC_ROWS,
  ONLINE_SITE_ID,
  PAYMENT_METHODS_TO_JESTA_CODES,
  SEND_ORDER_RETRY_LIMIT,
  SENT_TO_OMS_STATUSES,
  TAXES_ROWS,
  TAXES_ROWS_ENUM,
  TENDER_ROWS,
  TENDER_ROWS_ENUM
}
