name: Docker Image build

on:
  push:
    branches: [ "main" ]
    
  # Allows you to run workflow manually from the actions tab
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v3
        with:
          # Fetch all commits
          fetch-depth: 0
          
      - name: Setup node and Run tests
        uses: actions/setup-node@v2
      - run: npm ci
      - run: npm run test
      
      - name: Tag new version
        id: release
        run: |
          git config --global user.name "github"
          git config --global user.email "github@users.noreply.github.com"
          npm version --patch
          VERSION=$(cat ./package.json | grep -m 1 version | sed 's/[^0-9.]//g')
          echo "::set-output name=version::$VERSION"
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/HarryRosen/hr-orders-service
          tags: |
            type=semver,pattern={{version}},value=${{ steps.release.outputs.version}}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.release.outputs.version}}
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to github container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push image
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Push release tag
        run: |
          git config pull.rebase true
          git pull
          git push --follow-tags
