name: Release Please
on:
  push:
    branches:
      - main
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release-please
        with:
          release-type: simple
          default-branch: main

      - name: Docker meta
        id: meta
        if : steps.release-please.outputs.release_created == 'true'
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/HarryRosen/hr-orders-service
          tags: |
            type=semver,pattern={{version}},value=${{ steps.release-please.outputs.tag_name }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.release-please.outputs.tag_name }}

      - name: Set up Docker Buildx
        id: buildx
        if : steps.release-please.outputs.release_created == 'true'
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to github container registry
        if : steps.release-please.outputs.release_created == 'true'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push image
        if : steps.release-please.outputs.release_created == 'true'
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}