name: Docker Image build

on:
  push:
    branches: [ "main" ]
    
  # Allows you to run workflow manually from the actions tab
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v3
        with:
          # Fetch all commits
          fetch-depth: 0
          
      - name: Setup node and Run tests
        uses: actions/setup-node@v2
      - run: npm ci
      - run: npm run test
      
      - name: Semantic versioning
        id: versioning
        uses: PaulHatch/semantic-version@v4.0.2
        with:
         branch: main
         tag_prefix: "v"
         major_pattern: "BREAKING_CHANGE:"
         minor_pattern: "feat:"
         format: "v${major}.${minor}.${patch}-prerelease${increment}"
      
      - name: Build the tagged Docker image
        run: docker build . --file Dockerfile --tag hr-orders-service:${{steps.versioning.outputs.version}}
      
      - name: Build the latest Docker image
        run: docker build . --file Dockerfile --tag hr-orders-service:latest
        
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
           tag_name: ${{ steps.versioning.outputs.version }}
           release_name: ${{ steps.versioning.outputs.version }}
           prerelease: true