name: sizing

on: [pull_request]

jobs:
  sizing:
    runs-on: ubuntu-latest
    name: Label PR size
    steps:
      - uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: 'size/xs'
          xs_max_size: '10'
          s_label: 'size/s'
          s_max_size: '100'
          m_label: 'size/m'
          m_max_size: '500'
          l_label: 'size/l'
          l_max_size: '1000'
          xl_label: 'size/xl'
          fail_if_xl: 'false'
          message_if_xl: >
            :warning: This PR exceeds the recommended size of 1000 lines. This **PR cannot be merged** without a team meeting to discuss impact. :warning:
          files_to_ignore: 'yarn.lock package-lock.json'
