# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test

on:
  pull_request:
  push:
    branches:
      - master
  

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup node 16.5.0
      uses: actions/setup-node@v2
      with:
        node-version: 16.5.x
    - run: npm install
    - run: npm run test
